version: "3"
services:

  db:
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    restart: always

  app:
    build: ./
    command: ./app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db