version: "3"
services:

  db:
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    restart: always

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    restart: on-failure


  app:
    build: ./
    command: ./app
    restart: always
    ports:
        - "8080:8080"
    depends_on:
        - db
        - cache
